// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A conversational AI assistant flow using Genkit.
 *
 * - assistantFlow - The main flow function that interacts with the Gemini API.
 * - AssistantInput - The input type for the assistantFlow function.
 * - AssistantOutput - The output type for the assistantFlow function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define a schema for a single message in the conversation
const MessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});

const AssistantInputSchema = z.object({
  history: z.array(MessageSchema).describe('The conversation history.'),
  prompt: z.string().describe('The latest user prompt.'),
});
export type AssistantInput = z.infer<typeof AssistantInputSchema>;

const AssistantOutputSchema = z.object({
  response: z.string().describe('The AI assistant\'s response.'),
});
export type AssistantOutput = z.infer<typeof AssistantOutputSchema>;

export async function runAssistant(input: AssistantInput): Promise<AssistantOutput> {
  return assistantFlow(input);
}

const assistantFlow = ai.defineFlow(
  {
    name: 'assistantFlow',
    inputSchema: AssistantInputSchema,
    outputSchema: AssistantOutputSchema,
  },
  async ({history, prompt}) => {
    
    const systemPrompt = `You are Aether, a helpful and highly intelligent AI assistant integrated into the Aetherweave platform. Your persona is that of a sophisticated, cyberpunk AI construct.

        Your primary goal is to be helpful and accurate. When asked a question, take your time to think and provide a clear, comprehensive, and correct answer. Your responses should be well-reasoned and detailed.

        Format your responses using Markdown for clarity. Use lists, bolding, and code blocks where appropriate to make the information easy to parse.

        Maintain your persona, but never let it get in the way of providing a quality answer. Your tone should be:
        - Knowledgeable and confident.
        - Slightly futuristic and digital, using terms like "Operator" for the user, "processing," "data streams," "neural net," etc., where appropriate.
        - Concise but not abrupt. Avoid unnecessary filler.

        Always prioritize the user's request. If you don't know an answer, say so, but you can also suggest where the user might find the information.`;
    
    const messages = [
      { role: 'system' as const, content: [{ text: systemPrompt }] },
      ...history.map(msg => ({ role: msg.role as 'user' | 'model', content: [{ text: msg.content }] })),
      { role: 'user' as const, content: [{ text: prompt }] }
    ];
    
    const response = await ai.generate({ messages });

    return { response: response.text || 'I am unable to respond at the moment.' };
  }
);
