// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates meeting notes from chat history using Genkit.
 *
 * - generateMeetingNotes - A function that generates meeting notes from chat history.
 * - GenerateMeetingNotesInput - The input type for the generateMeetingNotes function.
 * - GenerateMeetingNotesOutput - The output type for the generateMeetingNotes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMeetingNotesInputSchema = z.object({
  chatHistory: z
    .string()
    .describe('The complete chat history of the meeting.'),
});
export type GenerateMeetingNotesInput = z.infer<typeof GenerateMeetingNotesInputSchema>;

const GenerateMeetingNotesOutputSchema = z.object({
  notes: z.string().describe('The generated meeting notes summarizing key decisions and action items.'),
});
export type GenerateMeetingNotesOutput = z.infer<typeof GenerateMeetingNotesOutputSchema>;

export async function generateMeetingNotes(input: GenerateMeetingNotesInput): Promise<GenerateMeetingNotesOutput> {
  return generateMeetingNotesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMeetingNotesPrompt',
  input: {schema: GenerateMeetingNotesInputSchema},
  output: {schema: GenerateMeetingNotesOutputSchema},
  prompt: `You are an AI assistant tasked with generating meeting notes from a chat history.

  Please summarize the key decisions, action items, and important discussion points from the following chat history:

  {{chatHistory}}

  Present the notes in a clear and concise manner, suitable for easy review.
  The generated notes should be well-organized, highlighting the most important information discussed during the meeting.
  Avoid including greetings and closing remarks.
  Use proper markdown formatting.
  Include section titles such as:
  - Attendees
  - Key Discussions
  - Decisions Made
  - Action Items
  `,
});

const generateMeetingNotesFlow = ai.defineFlow(
  {
    name: 'generateMeetingNotesFlow',
    inputSchema: GenerateMeetingNotesInputSchema,
    outputSchema: GenerateMeetingNotesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
