github.com:
    users:
        linuxhackerkali77:
            oauth_token: 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
    git_protocol: https
    user: linuxhackerkali77
    oauth_token: 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
